name: Build releases

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  build:
    name: Build ${{ matrix.model }}-${{ matrix.version }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        model:
          - friendlyarm_nanopi-r2c
          - friendlyarm_nanopi-r2s
          - friendlyarm_nanopi-r3s
          - friendlyarm_nanopi-r4s
          - x86_64
        version:
          - openwrt-25.12

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        path: openwrt-actions-builder
        
    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][5-9]/p' | sed -n 1p | sed 's/.tar.gz//g')"
        echo "script_url=http://127.0.0.1:8080" >> "$GITHUB_ENV"
        echo "latest_release=$latest_release" >> "$GITHUB_ENV"

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Install Caddy Server
      run: |
        sudo curl -sL -o /usr/bin/caddy https://github.com/Xiaokailnol/openwrt-actions-builder/releases/download/caddy/caddy
        sudo chmod 755 /usr/bin/caddy
        echo ":8080 {" > caddyfile
        echo "    root * $(pwd)/openwrt-actions-builder" >> caddyfile
        echo "    file_server browse" >> caddyfile
        echo "}" >> caddyfile
        sudo /usr/bin/caddy start --config caddyfile --adapter caddyfile
        
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 512
        root-reserve-mb: 4608
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        remove-codeql: "true"

    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo /bin/bash -c "$(curl -sL https://git.io/vokNn)"
        sudo -E apt-fast -y -qq install asciidoc bash bcc bin86 binutils bison bzip2 clang file flex g++ g++-multilib gawk gcc-multilib gettext git gzip help2man intltool libbpf-dev libboost-dev libelf-dev libncurses-dev libssl-dev libthread-queue-any-perl libusb-dev libxml-parser-perl linux-tools-generic llvm make patch perl-modules pkg-config python3-dev python3-pip python3-pyelftools python3-setuptools rsync sharutils swig time unzip util-linux wget xsltproc zlib1g-dev zip zstd
        sudo -E apt-fast -y -qq install dos2unix dwarves jq npm quilt
        sudo -E npm install -g pnpm
        sudo -E npm install -g n
        sudo -E n stable
        pip3 install --user -U pylibfdt --break-system-packages
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        sudo -E git config --global core.abbrev auto
        df -h

    - name: Prepare Mixedwrt
      run: |
        sudo chown -R runner:runner /home/runner/work/openwrt-actions-builder
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/01_get_ready.sh)

    - name: Prepare Package
      working-directory: ${{ github.workspace }}/openwrt
      run: |      
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/02_prepare_package.sh)
        case "${{ matrix.model }}" in
          friendlyarm_nanopi-r2c|friendlyarm_nanopi-r2s)
            bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/R2S/02_target_only.sh)
            ;;
          friendlyarm_nanopi-r3s|friendlyarm_nanopi-r4s)
            bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/R4S/02_target_only.sh)
            ;;
          x86_64)
            bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/X86/02_target_only.sh)
            ;;
        esac
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/04_remove_upx.sh)

    - name: QTMDFW4
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        case "${{ matrix.model }}" in
          friendlyarm_nanopi-r2c)
            curl -fsSL ${{ env.script_url }}/SEED/R2C/config.seed -o .config
            ;;
          friendlyarm_nanopi-r2s)
            curl -fsSL ${{ env.script_url }}/SEED/R2S/config.seed -o .config
            ;;
          friendlyarm_nanopi-r3s)
            curl -fsSL ${{ env.script_url }}/SEED/R3S/config.seed -o .config
            ;;
          friendlyarm_nanopi-r4s)
            curl -fsSL ${{ env.script_url }}/SEED/R4S/config.seed -o .config
            ;;            
          x86_64)
            curl -fsSL ${{ env.script_url }}/SEED/X86/config.seed -o .config
            ;;
        esac 

    - name: Convert Translation
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/03_convert_translation.sh)
        
    - name: Add ACL
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/05_create_acl_for_luci.sh) -a

    - name: Fix Permissions
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/08_fix_permissions.sh)

    - name: Make Config
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make defconfig

    - name: Cache
      if: inputs.build_firmware
      uses: HiGarfield/cachewrtbuild@main
      with:
        mixkey: ${{ matrix.model }}
        prefix: ${{ github.workspace }}/openwrt
        
    - name: Make Download
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make download -j50
        make -j$(($(nproc) + 1)) package/network/utils/nftables/refresh V=s

    - name: Compile Openwrt
      working-directory: ${{ github.workspace }}/openwrt
      id: compile
      run: |
        IGNORE_ERRORS=1 make -j$(($(nproc) + 1))
      
    - name: Extensive logs after a failed compilation
      working-directory: ${{ github.workspace }}/openwrt
      if: steps.compile.outcome == 'failure'
      run: |
        make V=s

    - name: Prepare Firmware Files
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p rom info
        if [[ "${{ matrix.model }}" == friendlyarm_nanopi-* ]]; then
          cp -a openwrt/bin/targets/rockchip/*/*.img.gz rom/
          cp -a openwrt/bin/targets/rockchip/*/*.manifest info/manifest.txt
          cp -a openwrt/bin/targets/rockchip/*/config.buildinfo info/config.buildinfo
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          cp -a openwrt/bin/targets/x86/*/*-ext4-combined-efi.img.gz rom/
          cp -a openwrt/bin/targets/x86/*/*-squashfs-combined-efi.img.gz rom/
          cp -a openwrt/bin/targets/x86/*/*-generic-rootfs.tar.gz rom/
          cp -a openwrt/bin/targets/x86/*/*-generic.manifest info/manifest.txt
          cp -a openwrt/bin/targets/x86/*/config.buildinfo info/config.buildinfo
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        fi
        cd ..
        tar zcf rom/buildinfo_${{ matrix.model }}.tar.gz info

    - name: Create release
      uses: ncipollo/release-action@v1.20.0
      with:
        name: OpenWrt-${{ env.latest_release }}
        allowUpdates: true
        tag: ${{ env.latest_release }}
        commit: openwrt-25.12
        replacesArtifacts: true
        makeLatest: true
        oken: ${{ secrets.GITHUB_TOKEN }}
        artifacts: |
          ${{ github.workspace }}/rom/*
