name: Build releases

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  build:
    name: Build ${{ matrix.model }}-${{ matrix.version }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        model:
          - friendlyarm_nanopi-r2c
          - friendlyarm_nanopi-r2s
          - friendlyarm_nanopi-r3s
          - friendlyarm_nanopi-r4s
          - x86_64
        version:
          - openwrt-25.12

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        path: openwrt-actions-builder
        
    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][5-9]/p' | sed -n 1p | sed 's/.tar.gz//g')"
        echo build_dir="/builder" >> "$GITHUB_ENV"
        echo "script_url=http://127.0.0.1:8080" >> "$GITHUB_ENV"
        echo "latest_release=$latest_release" >> "$GITHUB_ENV"

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Install Caddy Server
      run: |
        sudo curl -sL -o /usr/bin/caddy https://github.com/Xiaokailnol/openwrt-actions-builder/releases/download/caddy/caddy
        sudo chmod 755 /usr/bin/caddy
        echo ":8080 {" > caddyfile
        echo "    root * $(pwd)/openwrt-actions-builder" >> caddyfile
        echo "    file_server browse" >> caddyfile
        echo "}" >> caddyfile
        sudo /usr/bin/caddy start --config caddyfile --adapter caddyfile
        
    - name: Free disk space
      uses: sbwml/actions@free-disk
      with:
        build-mount-path: /builder

    - name: Build System Setup
      uses: sbwml/actions@openwrt-build-setup

    - name: Install LLVM
      uses: sbwml/actions@install-llvm

    - name: Execute Custom Script
      working-directory: /builder
      run: |
        # Prepare environment
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/01_get_ready.sh)

        # Prepare packages
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/02_prepare_package.sh)

        # Device specific customization
        case "${{ matrix.model }}" in
          friendlyarm_nanopi-r2c|friendlyarm_nanopi-r2s)
            bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/R2S/02_target_only.sh)
            ;;
          friendlyarm_nanopi-r3s|friendlyarm_nanopi-r4s)
            bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/R4S/02_target_only.sh)
            ;;
          x86_64)
            bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/X86/02_target_only.sh)
            ;;
        esac

        # Convert translations
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/03_convert_translation.sh)

        # Remove UPX
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/04_remove_upx.sh)

        # Create LuCI ACL
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/05_create_acl_for_luci.sh)

        # Fix permissions
        bash <(curl -fsSL ${{ env.script_url }}/SCRIPTS/08_fix_permissions.sh)

    - name: Download OpenWrt Config
      working-directory: /builder
      run: |
        case "${{ matrix.model }}" in
          friendlyarm_nanopi-r2c)
            curl -fsSL ${{ env.script_url }}/SEED/R2C/config.seed -o openwrt/.config
            ;;
          friendlyarm_nanopi-r2s)
            curl -fsSL ${{ env.script_url }}/SEED/R2S/config.seed -o openwrt/.config
            ;;
          friendlyarm_nanopi-r3s)
            curl -fsSL ${{ env.script_url }}/SEED/R3S/config.seed -o openwrt/.config
            ;;
          friendlyarm_nanopi-r4s)
            curl -fsSL ${{ env.script_url }}/SEED/R4S/config.seed -o openwrt/.config
            ;;            
          x86_64)
            curl -fsSL ${{ env.script_url }}/SEED/X86/config.seed -o openwrt/.config
            ;;
        esac

    - name: Make Config
      working-directory: /builder
      run: |
        cd openwrt && make defconfig

    - name: Cache Toolchain
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: openwrt-${{ env.latest_release }}-${{ matrix.model }}
        prefix: ${{ env.build_dir }}/openwrt
        
    - name: Make Download
      working-directory: /builder
      run: |
        cd openwrt && make download -j50
        make -j$(($(nproc) + 1)) package/network/utils/nftables/refresh V=s

    - name: Compile Openwrt
      working-directory: /builder
      id: compile
      run: |
        cd openwrt
        IGNORE_ERRORS=1 make -j$(($(nproc) + 1))
      
    - name: Extensive logs after a failed compilation
      working-directory: /builder
      if: steps.compile.outcome == 'failure'
      run: |
        cd openwrt
        make V=s

    - name: Prepare Firmware Files
      working-directory: /builder
      run: |
        mkdir -p rom info
        if [[ "${{ matrix.model }}" == friendlyarm_nanopi-* ]]; then
          cp -a openwrt/bin/targets/rockchip/*/*.img.gz rom/
          cp -a openwrt/bin/targets/rockchip/*/*.manifest info/manifest.txt
          cp -a openwrt/bin/targets/rockchip/*/config.buildinfo info/config.buildinfo
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          cp -a openwrt/bin/targets/x86/*/*-ext4-combined-efi.img.gz rom/
          cp -a openwrt/bin/targets/x86/*/*-squashfs-combined-efi.img.gz rom/
          cp -a openwrt/bin/targets/x86/*/*-generic-rootfs.tar.gz rom/
          cp -a openwrt/bin/targets/x86/*/*-generic.manifest info/manifest.txt
          cp -a openwrt/bin/targets/x86/*/config.buildinfo info/config.buildinfo
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        fi
        cd ..
        tar zcf rom/buildinfo_${{ matrix.model }}.tar.gz info

    - name: Create release
      uses: ncipollo/release-action@v1.20.0
      with:
        name: OpenWrt-${{ env.latest_release }}
        allowUpdates: true
        tag: ${{ env.latest_release }}
        commit: openwrt-25.12
        replacesArtifacts: true
        makeLatest: true
        oken: ${{ secrets.GITHUB_TOKEN }}
        artifacts: |
          ${{ env.build_dir }}/rom/*
